name: CI

on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.20.0

      - name: Build the site
        run: |
          zola build --output-dir ./dist
