name: Deploy to GH Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'true'

    - uses: taiki-e/install-action@v2
      with:
        tool: zola@0.20.0

    - run: zola build --output-dir ./public

    - uses: actions/configure-pages@v3
    - uses: actions/upload-pages-artifact@v3
      with:
        path: "./public/"

    - uses: actions/deploy-pages@v4
      id: deployment
