name: Deploy to GH Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'true'

    - uses: taiki-e/install-action@v2
      with:
        tool: zola@0.20.0

    - run: |
        zola build --output-dir ./public

    - uses: actions/upload-pages-artifact@v3
      with:
        path: "./public/"
